# Generated by Django 6.0.4 on 2026-06-23 10:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_restaurantbranch_options_alter_tenant_options_and_more'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'ออเดอร์อีเวนต์', 'verbose_name_plural': 'ออเดอร์อีเวนต์'},
        ),
        migrations.AlterModelOptions(
            name='eventorderitem',
            options={'verbose_name': 'รายการออเดอร์อีเวนต์', 'verbose_name_plural': 'รายการออเดอร์อีเวนต์'},
        ),
        migrations.AlterModelOptions(
            name='eventsession',
            options={'ordering': ['-date'], 'verbose_name': 'งานอีเวนต์', 'verbose_name_plural': 'งานอีเวนต์'},
        ),
        migrations.AlterField(
            model_name='eventorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ'),
        ),
        migrations.AlterField(
            model_name='eventorder',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='ชื่อลูกค้า'),
        ),
        migrations.AlterField(
            model_name='eventorder',
            name='order_number',
            field=models.CharField(max_length=20, verbose_name='เลขออเดอร์'),
        ),
        migrations.AlterField(
            model_name='eventorder',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20, verbose_name='วิธีชำระ'),
        ),
        migrations.AlterField(
            model_name='eventorder',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='events.eventsession', verbose_name='งานอีเวนต์'),
        ),
        migrations.AlterField(
            model_name='eventorder',
            name='status',
            field=models.CharField(choices=[('pending', 'รอชำระ'), ('paid', 'ชำระแล้ว'), ('cancelled', 'ยกเลิก')], default='pending', max_length=20, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='eventorder',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ยอดก่อนหัก'),
        ),
        migrations.AlterField(
            model_name='eventorder',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ยอดรวม'),
        ),
        migrations.AlterField(
            model_name='eventorderitem',
            name='menu_item_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID เมนู'),
        ),
        migrations.AlterField(
            model_name='eventorderitem',
            name='menu_item_name',
            field=models.CharField(max_length=200, verbose_name='ชื่อเมนู'),
        ),
        migrations.AlterField(
            model_name='eventorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='events.eventorder', verbose_name='ออเดอร์'),
        ),
        migrations.AlterField(
            model_name='eventorderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='จำนวน'),
        ),
        migrations.AlterField(
            model_name='eventorderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาต่อหน่วย'),
        ),
        migrations.AlterField(
            model_name='eventsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ'),
        ),
        migrations.AlterField(
            model_name='eventsession',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='สร้างโดย'),
        ),
        migrations.AlterField(
            model_name='eventsession',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='วันที่'),
        ),
        migrations.AlterField(
            model_name='eventsession',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='สถานที่'),
        ),
        migrations.AlterField(
            model_name='eventsession',
            name='menu_snapshot',
            field=models.JSONField(default=list, verbose_name='สแนปช็อตเมนู'),
        ),
        migrations.AlterField(
            model_name='eventsession',
            name='name',
            field=models.CharField(max_length=200, verbose_name='ชื่องาน'),
        ),
        migrations.AlterField(
            model_name='eventsession',
            name='notes',
            field=models.TextField(blank=True, verbose_name='หมายเหตุ'),
        ),
        migrations.AlterField(
            model_name='eventsession',
            name='session_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='eventsession',
            name='status',
            field=models.CharField(choices=[('draft', 'ร่าง'), ('active', 'กำลังขาย'), ('closed', 'ปิดแล้ว')], default='draft', max_length=20, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='eventsession',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_sessions', to='accounts.tenant', verbose_name='ร้าน'),
        ),
        migrations.AlterField(
            model_name='eventsession',
            name='total_orders',
            field=models.PositiveIntegerField(default=0, verbose_name='จำนวนออเดอร์'),
        ),
        migrations.AlterField(
            model_name='eventsession',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='รายได้รวม'),
        ),
    ]
