# Generated by Django 6.0.4 on 2026-06-21 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_alter_restaurantbranch_options_alter_tenant_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='เช่น order.paid, po.created, stock.adjust', max_length=100, verbose_name='การกระทำ')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='โมเดล')),
                ('object_id', models.CharField(blank=True, max_length=50, verbose_name='รหัสอ้างอิง')),
                ('summary', models.CharField(blank=True, max_length=300, verbose_name='สรุป')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลา')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounts.tenant', verbose_name='ร้าน')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้')),
            ],
            options={
                'verbose_name': 'บันทึกการใช้งาน',
                'verbose_name_plural': 'บันทึกการใช้งาน',
                'db_table': 'core_auditlog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='core_auditl_tenant__93f9ab_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'ข้อมูล'), ('success', 'สำเร็จ'), ('warning', 'เตือน'), ('danger', 'ด่วน')], default='info', max_length=10, verbose_name='ระดับ')),
                ('category', models.CharField(choices=[('stock', 'สต็อก'), ('expiry', 'ของใกล้หมดอายุ'), ('reorder', 'สั่งซื้ออัตโนมัติ'), ('finance', 'การเงิน/P&L'), ('system', 'ระบบ')], default='system', max_length=20, verbose_name='หมวด')),
                ('title', models.CharField(max_length=200, verbose_name='หัวข้อ')),
                ('message', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('link', models.CharField(blank=True, help_text='URL ภายในระบบที่เกี่ยวข้อง', max_length=300, verbose_name='ลิงก์')),
                ('is_read', models.BooleanField(default=False, verbose_name='อ่านแล้ว')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.tenant', verbose_name='ร้าน')),
            ],
            options={
                'verbose_name': 'การแจ้งเตือน',
                'verbose_name_plural': 'การแจ้งเตือน',
                'db_table': 'core_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'is_read', '-created_at'], name='core_notifi_tenant__dde3da_idx')],
            },
        ),
    ]
