# Generated by Django 6.0.4 on 2026-04-11 23:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_restaurantbranch_tenant_user_avatar_user_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('position', models.CharField(choices=[('chef', 'เชฟ/พ่อครัว'), ('sous_chef', 'ผู้ช่วยเชฟ'), ('cook', 'แม่ครัว/คนครั��'), ('server', 'พนักงานเสิร์ฟ'), ('cashier', 'แคชเชียร์'), ('manager', 'ผู้จัดการ'), ('cleaner', 'แม่บ้าน'), ('other', 'อื่นๆ')], default='server', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('ot_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='accounts.tenant')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_employee',
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clock_in', models.TimeField(blank=True, null=True)),
                ('clock_out', models.TimeField(blank=True, null=True)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ot_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='hr.employee')),
            ],
            options={
                'db_table': 'hr_attendance',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('base_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ot_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sso_deduction', models.DecimalField(decimal_places=2, default=0, help_text='ประกันสังคม 5%', max_digits=8)),
                ('tax_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('other_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_ot_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll', to='hr.employee')),
            ],
            options={
                'db_table': 'hr_payroll',
                'ordering': ['-year', '-month'],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='ShiftSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift_type', models.CharField(choices=[('morning', 'เช้า (06:00-14:00)'), ('evening', 'บ่าย (14:00-22:00)'), ('split', 'สปลิท (10:00-14:00, 17:00-21:00)'), ('full', 'เต็มวัน (08:00-20:00)')], max_length=20)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='hr.employee')),
            ],
            options={
                'db_table': 'hr_shiftschedule',
                'ordering': ['date', 'employee'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
