# Generated by Django 6.0.4 on 2026-04-11 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollrecord',
            name='total_hours',
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='total_ot_hours',
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='days_worked',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='ot_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='regular_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
