# Generated by Django 6.0.4 on 2026-06-21 07:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_restaurantbranch_options_alter_tenant_options_and_more'),
        ('hr', '0002_hr_payroll_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date'], 'verbose_name': 'การเข้างาน', 'verbose_name_plural': 'การเข้างาน'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['first_name'], 'verbose_name': 'พนักงาน', 'verbose_name_plural': 'พนักงาน'},
        ),
        migrations.AlterModelOptions(
            name='payrollrecord',
            options={'ordering': ['-year', '-month'], 'verbose_name': 'บันทึกเงินเดือน', 'verbose_name_plural': 'บันทึกเงินเดือน'},
        ),
        migrations.AlterModelOptions(
            name='shiftschedule',
            options={'ordering': ['date', 'employee'], 'verbose_name': 'ตารางกะ', 'verbose_name_plural': 'ตารางกะ'},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='clock_in',
            field=models.TimeField(blank=True, null=True, verbose_name='เวลาเข้า'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='clock_out',
            field=models.TimeField(blank=True, null=True, verbose_name='เวลาออก'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(verbose_name='วันที่'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='hr.employee', verbose_name='พนักงาน'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='notes',
            field=models.CharField(blank=True, max_length=200, verbose_name='หมายเหตุ'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='ot_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='ชั่วโมง OT'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='ชั่วโมงรวม'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='เงินเดือนพื้นฐาน'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='ชื่อ'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='ค่าจ้างรายชั่วโมง'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='เปิดใช้งาน'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='นามสกุล'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, verbose_name='ชื่อเล่น'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ot_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='ค่า OT ต่อชั่วโมง'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='โทรศัพท์'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('chef', 'เชฟ/พ่อครัว'), ('sous_chef', 'ผู้ช่วยเชฟ'), ('cook', 'แม่ครัว/คนครัว'), ('server', 'พนักงานเสิร์ฟ'), ('cashier', 'แคชเชียร์'), ('manager', 'ผู้จัดการ'), ('cleaner', 'แม่บ้าน'), ('other', 'อื่นๆ')], default='server', max_length=20, verbose_name='ตำแหน่ง'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='วันเริ่มงาน'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='accounts.tenant', verbose_name='ร้าน'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้งาน'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='base_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='เงินเดือน'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='โบนัส'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='days_worked',
            field=models.PositiveIntegerField(default=0, verbose_name='วันทำงาน'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll', to='hr.employee', verbose_name='พนักงาน'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='gross_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='รายได้รวม'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='จ่ายแล้ว'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='month',
            field=models.PositiveIntegerField(verbose_name='เดือน'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='net_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='รายได้สุทธิ'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='ot_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='ชั่วโมง OT'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='ot_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ค่า OT'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='other_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='หักอื่นๆ'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='paid_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่จ่าย'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='regular_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='ชั่วโมงปกติ'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='sso_deduction',
            field=models.DecimalField(decimal_places=2, default=0, help_text='ประกันสังคม 5%', max_digits=8, verbose_name='หัก ประกันสังคม'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='tax_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='หัก ภาษี'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='year',
            field=models.PositiveIntegerField(verbose_name='ปี'),
        ),
        migrations.AlterField(
            model_name='shiftschedule',
            name='date',
            field=models.DateField(verbose_name='วันที่'),
        ),
        migrations.AlterField(
            model_name='shiftschedule',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='hr.employee', verbose_name='พนักงาน'),
        ),
        migrations.AlterField(
            model_name='shiftschedule',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='เวลาสิ้นสุด'),
        ),
        migrations.AlterField(
            model_name='shiftschedule',
            name='notes',
            field=models.CharField(blank=True, max_length=200, verbose_name='หมายเหตุ'),
        ),
        migrations.AlterField(
            model_name='shiftschedule',
            name='shift_type',
            field=models.CharField(choices=[('morning', 'เช้า (06:00-14:00)'), ('evening', 'บ่าย (14:00-22:00)'), ('split', 'สปลิท (10:00-14:00, 17:00-21:00)'), ('full', 'เต็มวัน (08:00-20:00)')], max_length=20, verbose_name='ประเภทกะ'),
        ),
        migrations.AlterField(
            model_name='shiftschedule',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='เวลาเริ่ม'),
        ),
    ]
