# Generated by Django 6.0.4 on 2026-04-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_restaurantbranch_tenant_user_avatar_user_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('gm', 'GM / Owner'), ('manager', 'Manager'), ('fb', 'FB (หน้าร้าน/บาร์)'), ('kt', 'KT (ครัว)')], default='fb', help_text='แผนกที่สังกัด — กำหนดหน้าที่เข้าถึงได้', max_length=10),
        ),
    ]
