# Generated by Django 6.0.4 on 2026-06-21 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantbranch',
            options={'verbose_name': 'สาขา', 'verbose_name_plural': 'สาขา'},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'verbose_name': 'ร้าน', 'verbose_name_plural': 'ร้าน'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'ผู้ใช้งาน', 'verbose_name_plural': 'ผู้ใช้งาน'},
        ),
        migrations.AlterField(
            model_name='restaurantbranch',
            name='address',
            field=models.TextField(blank=True, verbose_name='ที่อยู่'),
        ),
        migrations.AlterField(
            model_name='restaurantbranch',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='เปิดใช้งาน'),
        ),
        migrations.AlterField(
            model_name='restaurantbranch',
            name='name',
            field=models.CharField(max_length=200, verbose_name='ชื่อสาขา'),
        ),
        migrations.AlterField(
            model_name='restaurantbranch',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='โทรศัพท์'),
        ),
        migrations.AlterField(
            model_name='restaurantbranch',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='accounts.tenant', verbose_name='ร้าน'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='เปิดใช้งาน'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=200, verbose_name='ชื่อร้าน'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/', verbose_name='รูปโปรไฟล์'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('gm', 'GM / Owner'), ('manager', 'Manager'), ('fb', 'FB (หน้าร้าน/บาร์)'), ('kt', 'KT (ครัว)')], default='fb', help_text='แผนกที่สังกัด — กำหนดหน้าที่เข้าถึงได้', max_length=10, verbose_name='แผนก'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='โทรศัพท์'),
        ),
        migrations.AlterField(
            model_name='user',
            name='restaurant_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='accounts.restaurantbranch', verbose_name='สาขา'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('staff', 'Staff'), ('readonly', 'Read Only')], default='staff', max_length=20, verbose_name='บทบาท'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.tenant', verbose_name='ร้าน'),
        ),
    ]
