# Generated by Django 6.0.4 on 2026-04-11 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_restaurantbranch_tenant_user_avatar_user_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('power_watts', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('temperature', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('humidity', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('ac_on', models.BooleanField(default=False)),
                ('estimated_cost_thb', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ac_logs', to='accounts.tenant')),
            ],
            options={
                'db_table': 'reports_acusagelog',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DailySalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dine_in_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('beverage_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bf_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('event_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_covers', models.PositiveIntegerField(default=0)),
                ('avg_check', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('food_cost_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('food_cost_theoretical', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_sales', to='accounts.tenant')),
            ],
            options={
                'db_table': 'reports_dailysales',
                'ordering': ['-date'],
                'unique_together': {('tenant', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyPL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('dine_in_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('beverage_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bf_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('event_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('food_cost_theoretical', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('food_cost_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('waste_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('variance_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('labour_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('electricity_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('food_cost_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('labour_cost_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('prime_cost_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_pl', to='accounts.tenant')),
            ],
            options={
                'db_table': 'reports_monthlypl',
                'ordering': ['-year', '-month'],
                'unique_together': {('tenant', 'month', 'year')},
            },
        ),
    ]
