# Generated by Django 6.0.4 on 2026-06-23 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_restaurantbranch_options_alter_tenant_options_and_more'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acusagelog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'บันทึกการใช้แอร์', 'verbose_name_plural': 'บันทึกการใช้แอร์'},
        ),
        migrations.AlterModelOptions(
            name='dailysalesrecord',
            options={'ordering': ['-date'], 'verbose_name': 'ยอดขายรายวัน', 'verbose_name_plural': 'ยอดขายรายวัน'},
        ),
        migrations.AlterModelOptions(
            name='monthlypl',
            options={'ordering': ['-year', '-month'], 'verbose_name': 'P&L รายเดือน', 'verbose_name_plural': 'P&L รายเดือน'},
        ),
        migrations.AlterField(
            model_name='acusagelog',
            name='ac_on',
            field=models.BooleanField(default=False, verbose_name='เปิดแอร์'),
        ),
        migrations.AlterField(
            model_name='acusagelog',
            name='device_id',
            field=models.CharField(max_length=50, verbose_name='Device ID'),
        ),
        migrations.AlterField(
            model_name='acusagelog',
            name='estimated_cost_thb',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='ค่าไฟโดยประมาณ (บาท)'),
        ),
        migrations.AlterField(
            model_name='acusagelog',
            name='humidity',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='ความชื้น'),
        ),
        migrations.AlterField(
            model_name='acusagelog',
            name='power_watts',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='กำลังไฟ (W)'),
        ),
        migrations.AlterField(
            model_name='acusagelog',
            name='temperature',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='อุณหภูมิ'),
        ),
        migrations.AlterField(
            model_name='acusagelog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ac_logs', to='accounts.tenant', verbose_name='ร้าน'),
        ),
        migrations.AlterField(
            model_name='acusagelog',
            name='timestamp',
            field=models.DateTimeField(verbose_name='เวลา'),
        ),
        migrations.AlterField(
            model_name='dailysalesrecord',
            name='avg_check',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='เฉลี่ยต่อคน'),
        ),
        migrations.AlterField(
            model_name='dailysalesrecord',
            name='beverage_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='รายได้เครื่องดื่ม'),
        ),
        migrations.AlterField(
            model_name='dailysalesrecord',
            name='bf_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='รายได้อาหารเช้า'),
        ),
        migrations.AlterField(
            model_name='dailysalesrecord',
            name='date',
            field=models.DateField(verbose_name='วันที่'),
        ),
        migrations.AlterField(
            model_name='dailysalesrecord',
            name='dine_in_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='รายได้ Dine-in'),
        ),
        migrations.AlterField(
            model_name='dailysalesrecord',
            name='event_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='รายได้อีเวนต์'),
        ),
        migrations.AlterField(
            model_name='dailysalesrecord',
            name='food_cost_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Food Cost จริง'),
        ),
        migrations.AlterField(
            model_name='dailysalesrecord',
            name='food_cost_theoretical',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Food Cost ทฤษฎี'),
        ),
        migrations.AlterField(
            model_name='dailysalesrecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_sales', to='accounts.tenant', verbose_name='ร้าน'),
        ),
        migrations.AlterField(
            model_name='dailysalesrecord',
            name='total_covers',
            field=models.PositiveIntegerField(default=0, verbose_name='จำนวน Covers'),
        ),
        migrations.AlterField(
            model_name='dailysalesrecord',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='รายได้รวม'),
        ),
        migrations.AlterField(
            model_name='monthlypl',
            name='beverage_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='รายได้เครื่องดื่ม'),
        ),
        migrations.AlterField(
            model_name='monthlypl',
            name='bf_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='รายได้อาหารเช้า'),
        ),
        migrations.AlterField(
            model_name='monthlypl',
            name='dine_in_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='รายได้ Dine-in'),
        ),
        migrations.AlterField(
            model_name='monthlypl',
            name='electricity_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ค่าไฟ'),
        ),
        migrations.AlterField(
            model_name='monthlypl',
            name='event_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='รายได้อีเวนต์'),
        ),
        migrations.AlterField(
            model_name='monthlypl',
            name='food_cost_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Food Cost จริง'),
        ),
        migrations.AlterField(
            model_name='monthlypl',
            name='food_cost_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Food Cost %'),
        ),
        migrations.AlterField(
            model_name='monthlypl',
            name='food_cost_theoretical',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Food Cost ทฤษฎี'),
        ),
        migrations.AlterField(
            model_name='monthlypl',
            name='gross_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='กำไรขั้นต้น'),
        ),
        migrations.AlterField(
            model_name='monthlypl',
            name='labour_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ต้นทุนแรงงาน'),
        ),
        migrations.AlterField(
            model_name='monthlypl',
            name='labour_cost_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Labour Cost %'),
        ),
        migrations.AlterField(
            model_name='monthlypl',
            name='month',
            field=models.PositiveIntegerField(verbose_name='เดือน'),
        ),
        migrations.AlterField(
            model_name='monthlypl',
            name='net_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='กำไรสุทธิ'),
        ),
        migrations.AlterField(
            model_name='monthlypl',
            name='other_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ค่าใช้จ่ายอื่นๆ'),
        ),
        migrations.AlterField(
            model_name='monthlypl',
            name='prime_cost_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Prime Cost %'),
        ),
        migrations.AlterField(
            model_name='monthlypl',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_pl', to='accounts.tenant', verbose_name='ร้าน'),
        ),
        migrations.AlterField(
            model_name='monthlypl',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='รายได้รวม'),
        ),
        migrations.AlterField(
            model_name='monthlypl',
            name='variance_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ส่วนต่าง Food Cost'),
        ),
        migrations.AlterField(
            model_name='monthlypl',
            name='waste_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ต้นทุนของเสีย'),
        ),
        migrations.AlterField(
            model_name='monthlypl',
            name='year',
            field=models.PositiveIntegerField(verbose_name='ปี'),
        ),
    ]
