# Generated by Django 6.0.4 on 2026-04-11 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_restaurantbranch_tenant_user_avatar_user_phone_and_more'),
        ('restaurant', '0002_pricehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuUpsellRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[('couple', 'คู่รัก (1ช+1ญ)'), ('has_children', 'มีเด็ก'), ('has_senior', 'มีผู้สูงอายุ'), ('group', 'กลุ่ม (4+ คน)'), ('men_only', 'ผู้ชายล้วน'), ('women_only', 'ผู้หญิงล้วน'), ('default', 'ทั่วไป')], max_length=20)),
                ('reason', models.CharField(help_text='เหตุผลสั้นๆ เช่น "เมนูแนะนำสำหรับคู่"', max_length=100)),
                ('priority', models.PositiveIntegerField(default=0, help_text='ยิ่งสูง ยิ่งแสดงก่อน')),
                ('is_active', models.BooleanField(default=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upsell_rules', to='restaurant.menuitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upsell_rules', to='accounts.tenant')),
            ],
            options={
                'db_table': 'pos_menuupsellrule',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('open', 'เปิดอยู่'), ('sent', 'ส่งครัวแล้ว'), ('served', 'เสิร์ฟแล้ว'), ('bill', 'รอเก็บเงิน'), ('paid', 'ชำระแล้ว'), ('cancelled', 'ยกเลิก')], default='open', max_length=20)),
                ('guest_count', models.PositiveIntegerField(default=1)),
                ('men_count', models.PositiveIntegerField(default=0)),
                ('women_count', models.PositiveIntegerField(default=0)),
                ('children_count', models.PositiveIntegerField(default=0)),
                ('senior_count', models.PositiveIntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.tenant')),
            ],
            options={
                'db_table': 'pos_order',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='KitchenTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'รอทำ'), ('in_progress', 'กำลังทำ'), ('done', 'เสร็จ')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_tickets', to='accounts.tenant')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_tickets', to='pos.order')),
            ],
            options={
                'db_table': 'pos_kitchenticket',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('special_request', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'รอส่งครัว'), ('sent', 'ส่งครัวแล้ว'), ('preparing', 'กำลังทำ'), ('ready', 'พร้อมเสิร์ฟ'), ('served', 'เสิร์ฟแล้ว'), ('voided', 'ยกเลิก')], default='pending', max_length=20)),
                ('is_voided', models.BooleanField(default=False)),
                ('void_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='restaurant.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.order')),
            ],
            options={
                'db_table': 'pos_orderitem',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='KitchenTicketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('special_request', models.CharField(blank=True, max_length=200)),
                ('is_done', models.BooleanField(default=False)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.kitchenticket')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_items', to='pos.orderitem')),
            ],
            options={
                'db_table': 'pos_kitchenticketitem',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('name', models.CharField(blank=True, help_text='เช่น โต๊ะริมน้ำ, ห้อง VIP', max_length=50)),
                ('capacity', models.PositiveIntegerField(default=4)),
                ('status', models.CharField(choices=[('empty', 'ว่าง'), ('occupied', 'มีลูกค้า'), ('bill_pending', 'รอเก็บเงิน'), ('reserved', 'จอง')], default='empty', max_length=20)),
                ('zone', models.CharField(blank=True, help_text='โซน เช่น ในร้าน, ริมน้ำ, ชั้น 2', max_length=50)),
                ('grid_x', models.PositiveIntegerField(default=0, help_text='ตำแหน่งบน floor plan')),
                ('grid_y', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='accounts.tenant')),
            ],
            options={
                'db_table': 'pos_table',
                'ordering': ['sort_order', 'number'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='pos.table'),
        ),
        migrations.AddField(
            model_name='kitchenticket',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.table'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cash', 'เงินสด'), ('card', 'บัตรเครดิต/เดบิต'), ('promptpay', 'QR PromptPay'), ('room_charge', 'เซ็นห้อง'), ('transfer', 'โอนเงิน')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('change', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reference', models.CharField(blank=True, help_text='เลขห้อง, ref number', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='pos.order')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.tenant')),
            ],
            options={
                'db_table': 'pos_transaction',
                'ordering': ['-created_at'],
            },
        ),
    ]
