# Generated by Django 6.0.4 on 2026-04-11 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_hr_payroll_fields'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenticket',
            name='prepared_by',
            field=models.ForeignKey(blank=True, help_text='เชฟ/คนครัวที่รับผิดชอบ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitchen_tickets', to='hr.employee'),
        ),
    ]
