# Generated by Django 6.0.4 on 2026-06-21 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_restaurantbranch_options_alter_tenant_options_and_more'),
        ('hr', '0003_alter_attendance_options_alter_employee_options_and_more'),
        ('pos', '0002_kitchen_prepared_by'),
        ('restaurant', '0005_alter_category_options_alter_item_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kitchenticket',
            options={'ordering': ['-created_at'], 'verbose_name': 'ใบสั่งครัว', 'verbose_name_plural': 'ใบสั่งครัว'},
        ),
        migrations.AlterModelOptions(
            name='kitchenticketitem',
            options={'verbose_name': 'รายการใบสั่งครัว', 'verbose_name_plural': 'รายการใบสั่งครัว'},
        ),
        migrations.AlterModelOptions(
            name='menuupsellrule',
            options={'ordering': ['-priority'], 'verbose_name': 'กฎ Upsell', 'verbose_name_plural': 'กฎ Upsell'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-opened_at'], 'verbose_name': 'ออเดอร์', 'verbose_name_plural': 'ออเดอร์'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['created_at'], 'verbose_name': 'รายการออเดอร์', 'verbose_name_plural': 'รายการออเดอร์'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['sort_order', 'number'], 'verbose_name': 'โต๊ะ', 'verbose_name_plural': 'โต๊ะ'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'รายการชำระเงิน', 'verbose_name_plural': 'รายการชำระเงิน'},
        ),
        migrations.AddField(
            model_name='order',
            name='stock_depleted',
            field=models.BooleanField(default=False, help_text='ระบบตั้งให้อัตโนมัติเมื่อตัดวัตถุดิบตามสูตรแล้ว', verbose_name='ตัดสต็อกแล้ว'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cost_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, help_text='ต้นทุนจริงที่ตัดจากสต็อก (FIFO) เมื่อขาย — ใช้คำนวณ Food Cost จริง', max_digits=10, verbose_name='ต้นทุนวัตถุดิบจริง'),
        ),
        migrations.AlterField(
            model_name='kitchenticket',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='เสร็จเมื่อ'),
        ),
        migrations.AlterField(
            model_name='kitchenticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ'),
        ),
        migrations.AlterField(
            model_name='kitchenticket',
            name='notes',
            field=models.TextField(blank=True, verbose_name='หมายเหตุ'),
        ),
        migrations.AlterField(
            model_name='kitchenticket',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_tickets', to='pos.order', verbose_name='ออเดอร์'),
        ),
        migrations.AlterField(
            model_name='kitchenticket',
            name='prepared_by',
            field=models.ForeignKey(blank=True, help_text='เชฟ/คนครัวที่รับผิดชอบ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitchen_tickets', to='hr.employee', verbose_name='ผู้รับผิดชอบ'),
        ),
        migrations.AlterField(
            model_name='kitchenticket',
            name='status',
            field=models.CharField(choices=[('pending', 'รอทำ'), ('in_progress', 'กำลังทำ'), ('done', 'เสร็จ')], default='pending', max_length=20, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='kitchenticket',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.table', verbose_name='โต๊ะ'),
        ),
        migrations.AlterField(
            model_name='kitchenticket',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_tickets', to='accounts.tenant', verbose_name='ร้าน'),
        ),
        migrations.AlterField(
            model_name='kitchenticket',
            name='ticket_number',
            field=models.CharField(max_length=20, verbose_name='เลข Ticket'),
        ),
        migrations.AlterField(
            model_name='kitchenticketitem',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='ทำเสร็จแล้ว'),
        ),
        migrations.AlterField(
            model_name='kitchenticketitem',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_items', to='pos.orderitem', verbose_name='รายการออเดอร์'),
        ),
        migrations.AlterField(
            model_name='kitchenticketitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='จำนวน'),
        ),
        migrations.AlterField(
            model_name='kitchenticketitem',
            name='special_request',
            field=models.CharField(blank=True, max_length=200, verbose_name='คำขอพิเศษ'),
        ),
        migrations.AlterField(
            model_name='kitchenticketitem',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.kitchenticket', verbose_name='ใบสั่งครัว'),
        ),
        migrations.AlterField(
            model_name='menuupsellrule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='เปิดใช้งาน'),
        ),
        migrations.AlterField(
            model_name='menuupsellrule',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upsell_rules', to='restaurant.menuitem', verbose_name='เมนู'),
        ),
        migrations.AlterField(
            model_name='menuupsellrule',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='ยิ่งสูง ยิ่งแสดงก่อน', verbose_name='ลำดับความสำคัญ'),
        ),
        migrations.AlterField(
            model_name='menuupsellrule',
            name='profile_type',
            field=models.CharField(choices=[('couple', 'คู่รัก (1ช+1ญ)'), ('has_children', 'มีเด็ก'), ('has_senior', 'มีผู้สูงอายุ'), ('group', 'กลุ่ม (4+ คน)'), ('men_only', 'ผู้ชายล้วน'), ('women_only', 'ผู้หญิงล้วน'), ('default', 'ทั่วไป')], max_length=20, verbose_name='ประเภทลูกค้า'),
        ),
        migrations.AlterField(
            model_name='menuupsellrule',
            name='reason',
            field=models.CharField(help_text='เหตุผลสั้นๆ เช่น "เมนูแนะนำสำหรับคู่"', max_length=100, verbose_name='เหตุผล'),
        ),
        migrations.AlterField(
            model_name='menuupsellrule',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upsell_rules', to='accounts.tenant', verbose_name='ร้าน'),
        ),
        migrations.AlterField(
            model_name='order',
            name='children_count',
            field=models.PositiveIntegerField(default=0, verbose_name='เด็ก'),
        ),
        migrations.AlterField(
            model_name='order',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ปิดเมื่อ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_created', to=settings.AUTH_USER_MODEL, verbose_name='สร้างโดย'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ส่วนลด'),
        ),
        migrations.AlterField(
            model_name='order',
            name='guest_count',
            field=models.PositiveIntegerField(default=1, verbose_name='จำนวนลูกค้า'),
        ),
        migrations.AlterField(
            model_name='order',
            name='men_count',
            field=models.PositiveIntegerField(default=0, verbose_name='ผู้ชาย'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, verbose_name='หมายเหตุ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='opened_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='เปิดเมื่อ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=20, verbose_name='เลขออเดอร์'),
        ),
        migrations.AlterField(
            model_name='order',
            name='senior_count',
            field=models.PositiveIntegerField(default=0, verbose_name='ผู้สูงอายุ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ค่าบริการ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('open', 'เปิดอยู่'), ('sent', 'ส่งครัวแล้ว'), ('served', 'เสิร์ฟแล้ว'), ('bill', 'รอเก็บเงิน'), ('paid', 'ชำระแล้ว'), ('cancelled', 'ยกเลิก')], default='open', max_length=20, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ยอดก่อนหัก'),
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='pos.table', verbose_name='โต๊ะ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.tenant', verbose_name='ร้าน'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ยอดรวม'),
        ),
        migrations.AlterField(
            model_name='order',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='VAT'),
        ),
        migrations.AlterField(
            model_name='order',
            name='women_count',
            field=models.PositiveIntegerField(default=0, verbose_name='ผู้หญิง'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='is_voided',
            field=models.BooleanField(default=False, verbose_name='ยกเลิกแล้ว'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='restaurant.menuitem', verbose_name='เมนู'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.order', verbose_name='ออเดอร์'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='จำนวน'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='served_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='เสิร์ฟเมื่อ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='special_request',
            field=models.CharField(blank=True, max_length=200, verbose_name='คำขอพิเศษ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'รอส่งครัว'), ('sent', 'ส่งครัวแล้ว'), ('preparing', 'กำลังทำ'), ('ready', 'พร้อมเสิร์ฟ'), ('served', 'เสิร์ฟแล้ว'), ('voided', 'ยกเลิก')], default='pending', max_length=20, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาต่อหน่วย'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='void_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='เหตุผลยกเลิก'),
        ),
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.PositiveIntegerField(default=4, verbose_name='ความจุ'),
        ),
        migrations.AlterField(
            model_name='table',
            name='grid_x',
            field=models.PositiveIntegerField(default=0, help_text='ตำแหน่งบน floor plan', verbose_name='ตำแหน่ง X'),
        ),
        migrations.AlterField(
            model_name='table',
            name='grid_y',
            field=models.PositiveIntegerField(default=0, verbose_name='ตำแหน่ง Y'),
        ),
        migrations.AlterField(
            model_name='table',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='เปิดใช้งาน'),
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(blank=True, help_text='เช่น โต๊ะริมน้ำ, ห้อง VIP', max_length=50, verbose_name='ชื่อ'),
        ),
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.CharField(max_length=10, verbose_name='หมายเลขโต๊ะ'),
        ),
        migrations.AlterField(
            model_name='table',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ลำดับ'),
        ),
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('empty', 'ว่าง'), ('occupied', 'มีลูกค้า'), ('bill_pending', 'รอเก็บเงิน'), ('reserved', 'จอง')], default='empty', max_length=20, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='table',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='accounts.tenant', verbose_name='ร้าน'),
        ),
        migrations.AlterField(
            model_name='table',
            name='zone',
            field=models.CharField(blank=True, help_text='โซน เช่น ในร้าน, ริมน้ำ, ชั้น 2', max_length=50, verbose_name='โซน'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='จำนวนเงิน'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='change',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ทอน'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='pos.order', verbose_name='ออเดอร์'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'เงินสด'), ('card', 'บัตรเครดิต/เดบิต'), ('promptpay', 'QR PromptPay'), ('room_charge', 'เซ็นห้อง'), ('transfer', 'โอนเงิน')], max_length=20, verbose_name='วิธีชำระ'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='processed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ดำเนินการโดย'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='รับมา'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(blank=True, help_text='เลขห้อง, ref number', max_length=100, verbose_name='อ้างอิง'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.tenant', verbose_name='ร้าน'),
        ),
    ]
