# Generated by Django 6.0.4 on 2026-06-24 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_restaurantbranch_options_alter_tenant_options_and_more'),
        ('pos', '0003_alter_kitchenticket_options_and_more'),
        ('restaurant', '0005_alter_category_options_alter_item_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='วันที่')),
                ('title', models.CharField(default='เป้าเชียร์ขายวันนี้', max_length=120, verbose_name='ชื่อแคมเปญ')),
                ('note', models.TextField(blank=True, help_text='ข้อความกระตุ้นทีม เช่น เน้นเชียร์ของหวาน', verbose_name='โน้ตถึงทีม')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ตั้งโดย')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='accounts.tenant', verbose_name='ร้าน')),
            ],
            options={
                'verbose_name': 'แคมเปญเชียร์ขาย',
                'verbose_name_plural': 'แคมเปญเชียร์ขาย',
                'db_table': 'pos_salescampaign',
                'ordering': ['-date'],
                'unique_together': {('tenant', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CampaignItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_qty', models.PositiveIntegerField(default=10, help_text='ทีมต้องขายรวมให้ได้กี่จานวันนี้', verbose_name='เป้าทีม (จาน)')),
                ('commission_per_dish', models.DecimalField(decimal_places=2, default=0, help_text='เงินที่คนขายได้รับต่อการขาย 1 จาน', max_digits=8, verbose_name='ค่าคอมต่อจาน')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_items', to='restaurant.menuitem', verbose_name='เมนู')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.salescampaign', verbose_name='แคมเปญ')),
            ],
            options={
                'verbose_name': 'เมนูเป้า',
                'verbose_name_plural': 'เมนูเป้า',
                'db_table': 'pos_campaignitem',
                'unique_together': {('campaign', 'menu_item')},
            },
        ),
    ]
