# Generated by Django 6.0.4 on 2026-04-11 02:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_restaurantbranch_tenant_user_avatar_user_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='accounts.tenant')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'restaurant_category',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='restaurant.category')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.tenant')),
            ],
            options={
                'db_table': 'restaurant_item',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('draft', 'ร่าง'), ('sent', 'ส่งแล้ว'), ('partial', 'รับบางส่วน'), ('received', 'รับครบ'), ('cancelled', 'ยกเลิก')], default='draft', max_length=20)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='accounts.tenant')),
            ],
            options={
                'db_table': 'restaurant_purchaseorder',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='POItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('received_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_items', to='restaurant.item')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurant.purchaseorder')),
            ],
            options={
                'db_table': 'restaurant_poitem',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('portions', models.PositiveIntegerField(default=1, help_text='จำนวนจานที่ได้จาก recipe นี้')),
                ('preparation_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='accounts.tenant')),
            ],
            options={
                'db_table': 'restaurant_recipe',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('menu_category', models.CharField(choices=[('appetizer', 'อาหารเรียกน้ำย่อย'), ('main', 'อาหารจานหลัก'), ('soup', 'แกง/ต้ม'), ('salad', 'ยำ/สลัด'), ('stir_fry', 'ผัด'), ('deep_fry', 'ทอด'), ('dessert', 'ของหวาน'), ('beverage', 'เครื่องดื่ม'), ('set_menu', 'ชุดเซ็ท')], default='main', max_length=20)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, upload_to='menu/')),
                ('is_available', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='accounts.tenant')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='restaurant.recipe')),
            ],
            options={
                'db_table': 'restaurant_menuitem',
                'ordering': ['menu_category', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counted_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('system_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('variance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('count_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('counted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='restaurant.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_counts', to='accounts.tenant')),
            ],
            options={
                'db_table': 'restaurant_stockcount',
                'ordering': ['-count_date'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'รับเข้า'), ('out', 'เบิกออก'), ('adjust', 'ปรับยอด'), ('waste', 'ทิ้ง/เสีย'), ('transfer', 'โอนย้าย')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='restaurant.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='accounts.tenant')),
            ],
            options={
                'db_table': 'restaurant_stockmovement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='restaurant.category')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='accounts.tenant')),
            ],
            options={
                'verbose_name_plural': 'Subcategories',
                'db_table': 'restaurant_subcategory',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='restaurant.subcategory'),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('line_id', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='accounts.tenant')),
            ],
            options={
                'db_table': 'restaurant_supplier',
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='restaurant.supplier'),
        ),
        migrations.CreateModel(
            name='LotBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(blank=True, max_length=50)),
                ('received_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='restaurant.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_batches', to='accounts.tenant')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.supplier')),
            ],
            options={
                'verbose_name_plural': 'Lot batches',
                'db_table': 'restaurant_lotbatch',
                'ordering': ['expiry_date', 'received_date'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='default_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='restaurant.supplier'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=10)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='accounts.tenant')),
            ],
            options={
                'db_table': 'restaurant_unit',
            },
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_uses', to='restaurant.item')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='restaurant.recipe')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.unit')),
            ],
            options={
                'db_table': 'restaurant_recipeitem',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='restaurant.unit'),
        ),
        migrations.CreateModel(
            name='WasteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('waste_date', models.DateField(default=django.utils.timezone.now)),
                ('reason', models.CharField(choices=[('expired', 'หมดอายุ'), ('over_prep', 'เตรียมเกิน'), ('dropped', 'ตกหล่น'), ('spoiled', 'เน่าเสีย'), ('other', 'อื่นๆ')], max_length=20)),
                ('cost_impact', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_records', to='restaurant.item')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_records', to='accounts.tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.unit')),
            ],
            options={
                'db_table': 'restaurant_wasterecord',
                'ordering': ['-waste_date'],
            },
        ),
        migrations.CreateModel(
            name='KPITarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('food_cost_target_pct', models.DecimalField(decimal_places=2, default=33, max_digits=5)),
                ('labour_cost_target_pct', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('revenue_target', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('waste_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prime_cost_target', models.DecimalField(decimal_places=2, default=63, max_digits=5)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_targets', to='accounts.tenant')),
            ],
            options={
                'db_table': 'restaurant_kpitarget',
                'unique_together': {('tenant', 'month', 'year')},
            },
        ),
    ]
