# Generated by Django 6.0.4 on 2026-04-11 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_restaurantbranch_tenant_user_avatar_user_phone_and_more'),
        ('restaurant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('reason', models.CharField(choices=[('market', 'ราคาตลาด'), ('seasonal', 'ตามฤดูกาล'), ('supplier', 'เปลี่ยน supplier'), ('war', 'สงคราม/วิกฤต'), ('other', 'อื่นๆ')], default='market', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_histories', to='restaurant.item')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.purchaseorder')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_histories', to='accounts.tenant')),
            ],
            options={
                'verbose_name_plural': 'Price histories',
                'db_table': 'restaurant_pricehistory',
                'ordering': ['-created_at'],
            },
        ),
    ]
