# Generated by Django 6.0.4 on 2026-04-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_pricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='prep_station',
            field=models.CharField(choices=[('kitchen', 'ครัว'), ('bar', 'บาร์/เครื่องดื่ม')], default='kitchen', help_text='ครัว = ส่ง KDS, บาร์ = FB ทำเอง ไม่ส่งครัว', max_length=10),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='prep_time_minutes',
            field=models.PositiveIntegerField(default=10, help_text='เวลาเตรียม (นาที)'),
        ),
    ]
