# Generated by Django 6.0.4 on 2026-04-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_menuitem_prep_station_menuitem_prep_time_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='menu_category',
            field=models.CharField(choices=[('soup', 'แกง'), ('stir_fry', 'ผัด'), ('boil', 'ต้ม'), ('deep_fry', 'ทอด'), ('chili_paste', 'ชุดน้ำพริก'), ('salad', 'ยำ'), ('steak', 'สเต๊ก'), ('single_dish', 'อาหารจานเดียว'), ('pasta', 'พาสต้า'), ('snack', 'อาหารทานเล่น'), ('dessert', 'ของหวาน'), ('cocktail', 'Cocktails'), ('mocktail', 'Mocktails'), ('smoothie', 'Smoothie / Shake'), ('coffee', 'Coffee & Tea'), ('beer', 'Beer'), ('soft_drink', 'Soft Drink'), ('set_menu', 'ชุดเซ็ท')], default='stir_fry', max_length=20),
        ),
    ]
