# Generated by Django 6.0.4 on 2026-06-21 07:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_restaurantbranch_options_alter_tenant_options_and_more'),
        ('restaurant', '0004_alter_menuitem_menu_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'หมวดหมู่', 'verbose_name_plural': 'หมวดหมู่'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['category', 'name'], 'verbose_name': 'วัตถุดิบ', 'verbose_name_plural': 'วัตถุดิบ'},
        ),
        migrations.AlterModelOptions(
            name='kpitarget',
            options={'verbose_name': 'เป้าหมาย KPI', 'verbose_name_plural': 'เป้าหมาย KPI'},
        ),
        migrations.AlterModelOptions(
            name='lotbatch',
            options={'ordering': ['expiry_date', 'received_date'], 'verbose_name': 'ล็อตสินค้า', 'verbose_name_plural': 'ล็อตสินค้า'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['menu_category', 'sort_order', 'name'], 'verbose_name': 'เมนู', 'verbose_name_plural': 'เมนู'},
        ),
        migrations.AlterModelOptions(
            name='poitem',
            options={'verbose_name': 'รายการสั่งซื้อ', 'verbose_name_plural': 'รายการสั่งซื้อ'},
        ),
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'ประวัติราคา', 'verbose_name_plural': 'ประวัติราคา'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-order_date'], 'verbose_name': 'ใบสั่งซื้อ', 'verbose_name_plural': 'ใบสั่งซื้อ'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'สูตรอาหาร', 'verbose_name_plural': 'สูตรอาหาร'},
        ),
        migrations.AlterModelOptions(
            name='recipeitem',
            options={'verbose_name': 'ส่วนผสม', 'verbose_name_plural': 'ส่วนผสม'},
        ),
        migrations.AlterModelOptions(
            name='stockcount',
            options={'ordering': ['-count_date'], 'verbose_name': 'การนับสต็อก', 'verbose_name_plural': 'การนับสต็อก'},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at'], 'verbose_name': 'การเคลื่อนไหวสต็อก', 'verbose_name_plural': 'การเคลื่อนไหวสต็อก'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'หมวดหมู่ย่อย', 'verbose_name_plural': 'หมวดหมู่ย่อย'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'ผู้จำหน่าย', 'verbose_name_plural': 'ผู้จำหน่าย'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'หน่วย', 'verbose_name_plural': 'หน่วย'},
        ),
        migrations.AlterModelOptions(
            name='wasterecord',
            options={'ordering': ['-waste_date'], 'verbose_name': 'บันทึกของเสีย', 'verbose_name_plural': 'บันทึกของเสีย'},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='รายละเอียด'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ชื่อ'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ลำดับ'),
        ),
        migrations.AlterField(
            model_name='category',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='accounts.tenant', verbose_name='ร้าน'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='restaurant.category', verbose_name='หมวดหมู่'),
        ),
        migrations.AlterField(
            model_name='item',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ราคาต่อหน่วย'),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ'),
        ),
        migrations.AlterField(
            model_name='item',
            name='current_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='สต็อกปัจจุบัน'),
        ),
        migrations.AlterField(
            model_name='item',
            name='default_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='restaurant.supplier', verbose_name='ผู้จำหน่ายหลัก'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='เปิดใช้งาน'),
        ),
        migrations.AlterField(
            model_name='item',
            name='max_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='สูงสุด'),
        ),
        migrations.AlterField(
            model_name='item',
            name='min_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ขั้นต่ำ'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=200, verbose_name='ชื่อ'),
        ),
        migrations.AlterField(
            model_name='item',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='restaurant.subcategory', verbose_name='หมวดหมู่ย่อย'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.tenant', verbose_name='ร้าน'),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='restaurant.unit', verbose_name='หน่วย'),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ'),
        ),
        migrations.AlterField(
            model_name='kpitarget',
            name='food_cost_target_pct',
            field=models.DecimalField(decimal_places=2, default=33, max_digits=5, verbose_name='เป้า Food Cost (%)'),
        ),
        migrations.AlterField(
            model_name='kpitarget',
            name='labour_cost_target_pct',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=5, verbose_name='เป้า Labour Cost (%)'),
        ),
        migrations.AlterField(
            model_name='kpitarget',
            name='month',
            field=models.PositiveIntegerField(verbose_name='เดือน'),
        ),
        migrations.AlterField(
            model_name='kpitarget',
            name='prime_cost_target',
            field=models.DecimalField(decimal_places=2, default=63, max_digits=5, verbose_name='เป้า Prime Cost (%)'),
        ),
        migrations.AlterField(
            model_name='kpitarget',
            name='revenue_target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='เป้ารายได้'),
        ),
        migrations.AlterField(
            model_name='kpitarget',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_targets', to='accounts.tenant', verbose_name='ร้าน'),
        ),
        migrations.AlterField(
            model_name='kpitarget',
            name='waste_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='งบของเสีย'),
        ),
        migrations.AlterField(
            model_name='kpitarget',
            name='year',
            field=models.PositiveIntegerField(verbose_name='ปี'),
        ),
        migrations.AlterField(
            model_name='lotbatch',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาต่อหน่วย'),
        ),
        migrations.AlterField(
            model_name='lotbatch',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันหมดอายุ'),
        ),
        migrations.AlterField(
            model_name='lotbatch',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='restaurant.item', verbose_name='วัตถุดิบ'),
        ),
        migrations.AlterField(
            model_name='lotbatch',
            name='lot_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='เลข Lot'),
        ),
        migrations.AlterField(
            model_name='lotbatch',
            name='notes',
            field=models.TextField(blank=True, verbose_name='หมายเหตุ'),
        ),
        migrations.AlterField(
            model_name='lotbatch',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='จำนวน'),
        ),
        migrations.AlterField(
            model_name='lotbatch',
            name='received_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='วันที่รับ'),
        ),
        migrations.AlterField(
            model_name='lotbatch',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.supplier', verbose_name='ผู้จำหน่าย'),
        ),
        migrations.AlterField(
            model_name='lotbatch',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_batches', to='accounts.tenant', verbose_name='ร้าน'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, upload_to='menu/', verbose_name='รูปภาพ'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='พร้อมขาย'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu_category',
            field=models.CharField(choices=[('soup', 'แกง'), ('stir_fry', 'ผัด'), ('boil', 'ต้ม'), ('deep_fry', 'ทอด'), ('chili_paste', 'ชุดน้ำพริก'), ('salad', 'ยำ'), ('steak', 'สเต๊ก'), ('single_dish', 'อาหารจานเดียว'), ('pasta', 'พาสต้า'), ('snack', 'อาหารทานเล่น'), ('dessert', 'ของหวาน'), ('cocktail', 'Cocktails'), ('mocktail', 'Mocktails'), ('smoothie', 'Smoothie / Shake'), ('coffee', 'Coffee & Tea'), ('beer', 'Beer'), ('soft_drink', 'Soft Drink'), ('set_menu', 'ชุดเซ็ท')], default='stir_fry', max_length=20, verbose_name='หมวดเมนู'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=200, verbose_name='ชื่อ'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='ชื่อภาษาอังกฤษ'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='prep_station',
            field=models.CharField(choices=[('kitchen', 'ครัว'), ('bar', 'บาร์/เครื่องดื่ม')], default='kitchen', help_text='ครัว = ส่ง KDS, บาร์ = FB ทำเอง ไม่ส่งครัว', max_length=10, verbose_name='สถานีเตรียม'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='prep_time_minutes',
            field=models.PositiveIntegerField(default=10, help_text='เวลาเตรียม (นาที)', verbose_name='เวลาเตรียม (นาที)'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='restaurant.recipe', verbose_name='สูตร'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาขาย'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ลำดับ'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='accounts.tenant', verbose_name='ร้าน'),
        ),
        migrations.AlterField(
            model_name='poitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_items', to='restaurant.item', verbose_name='วัตถุดิบ'),
        ),
        migrations.AlterField(
            model_name='poitem',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurant.purchaseorder', verbose_name='ใบสั่งซื้อ'),
        ),
        migrations.AlterField(
            model_name='poitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='จำนวน'),
        ),
        migrations.AlterField(
            model_name='poitem',
            name='received_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='จำนวนที่รับแล้ว'),
        ),
        migrations.AlterField(
            model_name='poitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาต่อหน่วย'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='change_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='% เปลี่ยนแปลง'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_histories', to='restaurant.item', verbose_name='วัตถุดิบ'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='new_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาใหม่'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='notes',
            field=models.TextField(blank=True, verbose_name='หมายเหตุ'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='old_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาเดิม'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.purchaseorder', verbose_name='ใบสั่งซื้อ'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='reason',
            field=models.CharField(choices=[('market', 'ราคาตลาด'), ('seasonal', 'ตามฤดูกาล'), ('supplier', 'เปลี่ยน supplier'), ('war', 'สงคราม/วิกฤต'), ('other', 'อื่นๆ')], default='market', max_length=20, verbose_name='สาเหตุ'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='บันทึกโดย'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_histories', to='accounts.tenant', verbose_name='ร้าน'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='สร้างโดย'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='expected_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่คาดรับ'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='notes',
            field=models.TextField(blank=True, verbose_name='หมายเหตุ'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='วันสั่ง'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(max_length=50, verbose_name='เลข PO'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='received_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่รับจริง'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'ร่าง'), ('sent', 'ส่งแล้ว'), ('partial', 'รับบางส่วน'), ('received', 'รับครบ'), ('cancelled', 'ยกเลิก')], default='draft', max_length=20, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='restaurant.supplier', verbose_name='ผู้จำหน่าย'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='accounts.tenant', verbose_name='ร้าน'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, verbose_name='รายละเอียด'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='เปิดใช้งาน'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=200, verbose_name='ชื่อ'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='portions',
            field=models.PositiveIntegerField(default=1, help_text='จำนวนจานที่ได้จาก recipe นี้', verbose_name='จำนวนจาน'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_notes',
            field=models.TextField(blank=True, verbose_name='วิธีเตรียม'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='accounts.tenant', verbose_name='ร้าน'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_uses', to='restaurant.item', verbose_name='วัตถุดิบ'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='notes',
            field=models.CharField(blank=True, max_length=200, verbose_name='หมายเหตุ'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='จำนวน'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='restaurant.recipe', verbose_name='สูตร'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.unit', verbose_name='หน่วย'),
        ),
        migrations.AlterField(
            model_name='stockcount',
            name='count_date',
            field=models.DateField(verbose_name='วันที่นับ'),
        ),
        migrations.AlterField(
            model_name='stockcount',
            name='counted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='นับโดย'),
        ),
        migrations.AlterField(
            model_name='stockcount',
            name='counted_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='จำนวนนับได้'),
        ),
        migrations.AlterField(
            model_name='stockcount',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='restaurant.item', verbose_name='วัตถุดิบ'),
        ),
        migrations.AlterField(
            model_name='stockcount',
            name='notes',
            field=models.TextField(blank=True, verbose_name='หมายเหตุ'),
        ),
        migrations.AlterField(
            model_name='stockcount',
            name='system_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='จำนวนในระบบ'),
        ),
        migrations.AlterField(
            model_name='stockcount',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_counts', to='accounts.tenant', verbose_name='ร้าน'),
        ),
        migrations.AlterField(
            model_name='stockcount',
            name='variance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ส่วนต่าง'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='บันทึกโดย'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='restaurant.item', verbose_name='วัตถุดิบ'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'รับเข้า'), ('out', 'เบิกออก'), ('adjust', 'ปรับยอด'), ('waste', 'ทิ้ง/เสีย'), ('transfer', 'โอนย้าย')], max_length=10, verbose_name='ประเภท'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='notes',
            field=models.TextField(blank=True, verbose_name='หมายเหตุ'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='จำนวน'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reference',
            field=models.CharField(blank=True, max_length=200, verbose_name='อ้างอิง'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='accounts.tenant', verbose_name='ร้าน'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ราคาต่อหน่วย'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='restaurant.category', verbose_name='หมวดหมู่'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ชื่อ'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='accounts.tenant', verbose_name='ร้าน'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, verbose_name='ที่อยู่'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, verbose_name='ผู้ติดต่อ'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='อีเมล'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='เปิดใช้งาน'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='line_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Line ID'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=200, verbose_name='ชื่อ'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='notes',
            field=models.TextField(blank=True, verbose_name='หมายเหตุ'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='โทรศัพท์'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='accounts.tenant', verbose_name='ร้าน'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='abbreviation',
            field=models.CharField(max_length=10, verbose_name='ตัวย่อ'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=50, verbose_name='ชื่อ'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='accounts.tenant', verbose_name='ร้าน'),
        ),
        migrations.AlterField(
            model_name='wasterecord',
            name='cost_impact',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='มูลค่าความเสียหาย'),
        ),
        migrations.AlterField(
            model_name='wasterecord',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_records', to='restaurant.item', verbose_name='วัตถุดิบ'),
        ),
        migrations.AlterField(
            model_name='wasterecord',
            name='notes',
            field=models.TextField(blank=True, verbose_name='หมายเหตุ'),
        ),
        migrations.AlterField(
            model_name='wasterecord',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='จำนวน'),
        ),
        migrations.AlterField(
            model_name='wasterecord',
            name='reason',
            field=models.CharField(choices=[('expired', 'หมดอายุ'), ('over_prep', 'เตรียมเกิน'), ('dropped', 'ตกหล่น'), ('spoiled', 'เน่าเสีย'), ('other', 'อื่นๆ')], max_length=20, verbose_name='สาเหตุ'),
        ),
        migrations.AlterField(
            model_name='wasterecord',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='บันทึกโดย'),
        ),
        migrations.AlterField(
            model_name='wasterecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_records', to='accounts.tenant', verbose_name='ร้าน'),
        ),
        migrations.AlterField(
            model_name='wasterecord',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.unit', verbose_name='หน่วย'),
        ),
        migrations.AlterField(
            model_name='wasterecord',
            name='waste_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='วันที่บันทึก'),
        ),
    ]
