# Generated by Django 6.0.4 on 2026-06-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_category_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text='รหัสอ้างอิง เช่น FF-0001 (จาก Market List)', max_length=30, verbose_name='รหัสวัตถุดิบ'),
        ),
    ]
