# Generated by Django 6.0.4 on 2026-04-11 23:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_restaurantbranch_tenant_user_avatar_user_phone_and_more'),
        ('pos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10)),
                ('guest_name', models.CharField(max_length=200)),
                ('checkout_date', models.DateField()),
                ('package_type', models.CharField(blank=True, help_text='เช่น RO, BB, HB, FB', max_length=50)),
                ('bf_included', models.BooleanField(default=False)),
                ('fb_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('import_date', models.DateField(default=django.utils.timezone.now)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_list', to='accounts.tenant')),
            ],
            options={
                'db_table': 'hotel_guestlist',
                'ordering': ['room_number'],
            },
        ),
        migrations.CreateModel(
            name='HotelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pms_type', models.CharField(choices=[('ads', 'ADS Hotel PMS'), ('opera', 'Oracle Opera'), ('manual', 'Manual CSV')], default='ads', max_length=20)),
                ('api_url', models.URLField(blank=True)),
                ('api_key', models.CharField(blank=True, max_length=200)),
                ('sync_method', models.CharField(choices=[('api', 'API Integration'), ('csv', 'CSV Import'), ('manual', 'Manual Entry')], default='manual', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_config', to='accounts.tenant')),
            ],
            options={
                'db_table': 'hotel_config',
            },
        ),
        migrations.CreateModel(
            name='RoomCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10)),
                ('guest_name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'รอ FO อนุมัติ'), ('posted', 'โพสต์แล้ว'), ('rejected', 'ถูกปฏิเสธ')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.order')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_charges', to='accounts.tenant')),
            ],
            options={
                'db_table': 'hotel_roomcharge',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BFSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_covers', models.PositiveIntegerField(default=0)),
                ('bb_covers', models.PositiveIntegerField(default=0, help_text='Bed & Breakfast')),
                ('hb_covers', models.PositiveIntegerField(default=0, help_text='Half Board')),
                ('fb_covers', models.PositiveIntegerField(default=0, help_text='Full Board')),
                ('walkin_covers', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('approved', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bf_settlements', to='accounts.tenant')),
            ],
            options={
                'db_table': 'hotel_bfsettlement',
                'ordering': ['-date'],
                'unique_together': {('tenant', 'date')},
            },
        ),
    ]
