# Generated by Django 6.0.4 on 2026-06-23 10:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_restaurantbranch_options_alter_tenant_options_and_more'),
        ('hotel_integration', '0001_initial'),
        ('pos', '0003_alter_kitchenticket_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bfsettlement',
            options={'ordering': ['-date'], 'verbose_name': 'สรุปอาหารเช้า', 'verbose_name_plural': 'สรุปอาหารเช้า'},
        ),
        migrations.AlterModelOptions(
            name='guestlist',
            options={'ordering': ['room_number'], 'verbose_name': 'รายชื่อแขก', 'verbose_name_plural': 'รายชื่อแขก'},
        ),
        migrations.AlterModelOptions(
            name='hotelconfig',
            options={'verbose_name': 'ตั้งค่าโรงแรม', 'verbose_name_plural': 'ตั้งค่าโรงแรม'},
        ),
        migrations.AlterModelOptions(
            name='roomcharge',
            options={'ordering': ['-created_at'], 'verbose_name': 'เซ็นห้อง', 'verbose_name_plural': 'เซ็นห้อง'},
        ),
        migrations.AlterField(
            model_name='bfsettlement',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='อนุมัติแล้ว'),
        ),
        migrations.AlterField(
            model_name='bfsettlement',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='อนุมัติโดย'),
        ),
        migrations.AlterField(
            model_name='bfsettlement',
            name='bb_covers',
            field=models.PositiveIntegerField(default=0, help_text='Bed & Breakfast', verbose_name='BB Covers'),
        ),
        migrations.AlterField(
            model_name='bfsettlement',
            name='date',
            field=models.DateField(verbose_name='วันที่'),
        ),
        migrations.AlterField(
            model_name='bfsettlement',
            name='fb_covers',
            field=models.PositiveIntegerField(default=0, help_text='Full Board', verbose_name='FB Covers'),
        ),
        migrations.AlterField(
            model_name='bfsettlement',
            name='hb_covers',
            field=models.PositiveIntegerField(default=0, help_text='Half Board', verbose_name='HB Covers'),
        ),
        migrations.AlterField(
            model_name='bfsettlement',
            name='notes',
            field=models.TextField(blank=True, verbose_name='หมายเหตุ'),
        ),
        migrations.AlterField(
            model_name='bfsettlement',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bf_settlements', to='accounts.tenant', verbose_name='ร้าน'),
        ),
        migrations.AlterField(
            model_name='bfsettlement',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ยอดรวม'),
        ),
        migrations.AlterField(
            model_name='bfsettlement',
            name='total_covers',
            field=models.PositiveIntegerField(default=0, verbose_name='จำนวน Covers รวม'),
        ),
        migrations.AlterField(
            model_name='bfsettlement',
            name='walkin_covers',
            field=models.PositiveIntegerField(default=0, verbose_name='Walk-in Covers'),
        ),
        migrations.AlterField(
            model_name='guestlist',
            name='bf_included',
            field=models.BooleanField(default=False, verbose_name='รวมอาหารเช้า'),
        ),
        migrations.AlterField(
            model_name='guestlist',
            name='checkout_date',
            field=models.DateField(verbose_name='วันเช็คเอาต์'),
        ),
        migrations.AlterField(
            model_name='guestlist',
            name='fb_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='วงเงิน F&B'),
        ),
        migrations.AlterField(
            model_name='guestlist',
            name='guest_name',
            field=models.CharField(max_length=200, verbose_name='ชื่อแขก'),
        ),
        migrations.AlterField(
            model_name='guestlist',
            name='import_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='วันที่นำเข้า'),
        ),
        migrations.AlterField(
            model_name='guestlist',
            name='package_type',
            field=models.CharField(blank=True, help_text='เช่น RO, BB, HB, FB', max_length=50, verbose_name='ประเภทแพ็กเกจ'),
        ),
        migrations.AlterField(
            model_name='guestlist',
            name='room_number',
            field=models.CharField(max_length=10, verbose_name='เลขห้อง'),
        ),
        migrations.AlterField(
            model_name='guestlist',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_list', to='accounts.tenant', verbose_name='ร้าน'),
        ),
        migrations.AlterField(
            model_name='hotelconfig',
            name='api_key',
            field=models.CharField(blank=True, max_length=200, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='hotelconfig',
            name='api_url',
            field=models.URLField(blank=True, verbose_name='API URL'),
        ),
        migrations.AlterField(
            model_name='hotelconfig',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='เปิดใช้งาน'),
        ),
        migrations.AlterField(
            model_name='hotelconfig',
            name='pms_type',
            field=models.CharField(choices=[('ads', 'ADS Hotel PMS'), ('opera', 'Oracle Opera'), ('manual', 'Manual CSV')], default='ads', max_length=20, verbose_name='ประเภท PMS'),
        ),
        migrations.AlterField(
            model_name='hotelconfig',
            name='sync_method',
            field=models.CharField(choices=[('api', 'API Integration'), ('csv', 'CSV Import'), ('manual', 'Manual Entry')], default='manual', max_length=20, verbose_name='วิธี Sync'),
        ),
        migrations.AlterField(
            model_name='hotelconfig',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_config', to='accounts.tenant', verbose_name='ร้าน'),
        ),
        migrations.AlterField(
            model_name='roomcharge',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='จำนวนเงิน'),
        ),
        migrations.AlterField(
            model_name='roomcharge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ'),
        ),
        migrations.AlterField(
            model_name='roomcharge',
            name='guest_name',
            field=models.CharField(max_length=200, verbose_name='ชื่อแขก'),
        ),
        migrations.AlterField(
            model_name='roomcharge',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.order', verbose_name='ออเดอร์'),
        ),
        migrations.AlterField(
            model_name='roomcharge',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='โพสต์โดย'),
        ),
        migrations.AlterField(
            model_name='roomcharge',
            name='room_number',
            field=models.CharField(max_length=10, verbose_name='เลขห้อง'),
        ),
        migrations.AlterField(
            model_name='roomcharge',
            name='status',
            field=models.CharField(choices=[('pending', 'รอ FO อนุมัติ'), ('posted', 'โพสต์แล้ว'), ('rejected', 'ถูกปฏิเสธ')], default='pending', max_length=20, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='roomcharge',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_charges', to='accounts.tenant', verbose_name='ร้าน'),
        ),
    ]
